title: "Lise Savard"
description: "Lise Savard, Computer Engineering student at the University of British Columbia"
url: https://lise.me
google_analytics: UA-112459178-1

permalink: /posts/:title/

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed

include: ['_pages', 'robots.txt']
plugins: [jekyll-sitemap]

exclude: 
  - Gemfile
  - Gemfile.lock
  - _site
  - rakefile.rb
  - README.md
  - _ignore
  - _notes
  - .firebaserc
  - firebase.json
  - vendor

defaults:
  - values:
      layout: "default"
