title: "Lise Savard"
description: "Web site of Lise Savard, 3rd year Computer Engineering student at the University of British Columbia"
url: https://lise.me
google_analytics: UA-112459178-1

links:
  - name: About
    url: /
    external: false
  - name: Github
    url: https://github.com/lsav
    external: true
  - name: LinkedIn
    url: https://www.linkedin.com/in/lsava/
    external: true
  - name: Unsplash
    url: https://unsplash.com/@rampallion
    external: true

permalink: /posts/:title/

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
paginate: 10
paginate_path: "blog/:num/"

include: ['_pages', 'robots.txt']
plugins: [jekyll-sitemap, jekyll-paginate]

exclude: 
  - Gemfile
  - Gemfile.lock
  - _site
  - rakefile.rb
  - README.md
  - _ignore
  - _notes
  - .firebaserc
  - firebase.json
  - vendor

defaults:
  - values:
      layout: "default"
