title: "Lise Savard"
description: "Web site of Lise Savard, 3rd year Computer Engineering student at the University of British Columbia"
url: http://lisesavard.com
google_analytics: UA-112459178-1

links:
  - name: Blog
    url: /
    external: false
  - name: About
    url: /about
    external: false
  - name: LinkedIn
    url: https://www.linkedin.com/in/lsava/
    external: true

permalink: /posts/:title/

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
paginate: 10
paginate_path: ":num/"

include: ['_pages', 'robots.txt']
exclude: ['Gemfile', 'Gemfile.lock', '_site', 'rakefile.rb', 'README.md']
plugins: [jekyll-sitemap, jekyll-paginate]

defaults:
  - values:
      layout: "default"
